### ISSUE TITLE
Support Project Sail 

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-operator#298]
**What**

We would like to support using project sail as the way to install and configure Istio as a gateway provider.  We want to try out kuadrant with the latest of project sail as this will become a new release soon that supports istio 1.20

While we may want to automate some of the installation, it is not expected at this point that it will be the default way to install istio as part of Kuadrant

https://github.com/maistra/istio-operator/blob/maistra-3.0/bundle/README.md

- [x] Read and understand how to install project sail into a cluster
- [x] #299
- [x] Test Rate Limit Policy with a project sail installed instance of Istio 
- [x] Test AuthPolicy with a project sail installed instance of Istio 
- [x] #320
- [x] Update / Add any docs needed so that a user could do use project sail with Kuadrant by themselves

**Comment by alexsnaps** [comment]
> Put together a blog post on how you can use Kuadrant with project sail 3.0

We don't have a blog section on the website (that I know of), but thinking we should have a recipes page with "Getting started with Kuadrant on..."

**Comment by maleck13** [comment]
Yes I added a new bullet to update / add docs around using project sail with Kuadrant.

**Comment by maleck13** [comment]
I am not sure there is a need for any docs updates @adam-cattermole ? Perhaps calling out to setup with project sail you need to use make `make local-cluster-setup ISTIO_INSTALL_SAIL=true` ?
I have the blog post done.

**Comment by maleck13** [comment]
Ok cool! Can prob mark this as done then?

**Comment by maleck13** [comment]
This is followed up by a quickstart improvment https://github.com/Kuadrant/kuadrant-operator/issues/315
