### ISSUE TITLE
Kuadrant Release v0.5.0

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/kuadrant-operator#300]
# Release dependencies

 - [x] kuadrant-operator [v0.5.0](https://github.com/Kuadrant/kuadrant-operator/releases/tag/v0.5.0)
 - [x] limitador-operator [v0.7.0](https://github.com/Kuadrant/limitador-operator/releases/tag/v0.7.0)
 - [x] authorino-operator [v0.10.0](https://github.com/Kuadrant/authorino-operator/releases/tag/v0.10.0)
 - [x] authorino [v0.16.0](https://github.com/Kuadrant/authorino/releases/tag/v0.16.0)
 - [x] limitador [v1.3.0](https://github.com/Kuadrant/limitador/releases/tag/server-v1.3.0)
 - [x] wasm-shim [v0.3.0](https://github.com/Kuadrant/wasm-shim/releases/tag/v0.3.0)
