### ISSUE TITLE
Kuadrant sub component configuration

### ISSUE THREAD

**Issue by Boomatang** [Kuadrant/kuadrant-operator#308]
RFC: https://github.com/Kuadrant/architecture/blob/main/rfcs/0006-kuadrant_sub_components_configurations.md

This epic covers the work to implement the RFC.

## Required Tasks

- [x] https://github.com/Kuadrant/kuadrant-operator/issues/304
- [ ] https://github.com/Kuadrant/kuadrant-operator/issues/305
- [ ] https://github.com/Kuadrant/kuadrant-operator/issues/306
- [ ] https://github.com/Kuadrant/kuadrant-operator/issues/307
- [x] https://github.com/Kuadrant/kuadrant-operator/issues/163

**Comment by Boomatang** [comment]
Closing: a number of issue with this, work even got reverted.
