### ISSUE TITLE
Add a quickstart for a single cluster

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-operator#315]
**What**
In a similar vein to what we did with the MGC, I think ideally we would have a quick start script that setup the single cluster environment ready for users to try out. 
- local kind cluster, 
- installed the required infrastructure (Istio, metallb, cert-manager, olm etc....) 
- install the latest release or a specified release of the kuadrant-operator (based on $BRANCH)
- instantiate any needed infra CRs (metallb, clusterissuer etc )
- optionally set up a DNSProvider secret and ManagedZone

Additionally we should provide a new quickstart doc focused around this single cluster setup that provides a walkthrough from deploying a gateway and backed to securing that service with Auth, RateLimits, TLS and then finally brining traffic to the backend with DNSPolicy using a simple routing policy. 

**Done**

- [x] #370
- [x] #361 (https://github.com/Kuadrant/kuadrant-operator/pull/362)
- [x] Single Cluster Getting Started (https://github.com/Kuadrant/docs.kuadrant.io/pull/44)
- [x] New Link aded to the docs.kuadrant.io under `Getting Started: single cluster`

**Comment by maleck13** [comment]
see https://github.com/Kuadrant/docs.kuadrant.io/pull/44 for more on the proposed nav layout
