### ISSUE TITLE
Create a test e2e plan

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/kuadrant-operator#39]
## Test scenarii

- [ ] Installation itself
- [ ] RLP happy path (add, mod, delete CRs)
- [ ] AP happy path (add, mod, delete CRs)
- [ ] "invalid" services  (e.g. no Istio)
- [ ] invalid CRs (test status)
- [ ] Transient failures?
- [ ] Uninstall

## Implementation considerations

- Test should "only" use public APIs (i.e. CRs) and test for expected outcome, e.g. the service is rate limited.
- It's fine to have transient failures because of out-of-sync dependencies. Let's see how much we get, why we get them and re-assess if these become "too many".
- Defer to kcp to actual testing implementation (for future safe testing, when integrating with them)

**Comment by eguzki** [comment]
What about testing the user guides? That is, implement the user guides workflow adding assertions  to make sure the state is what is should be at any intermediate step.
