### ISSUE TITLE
Dev Preview release `rc1`

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/kuadrant-operator#40]
- [x] [kuadrant-operator](https://github.com/Kuadrant/kuadrant-operator): [v.0.2.0](https://github.com/Kuadrant/kuadrant-operator/milestone/1)
   - [x] [kuadrant-controller](https://github.com/Kuadrant/kuadrant-controller): [v0.4.0](https://github.com/Kuadrant/kuadrant-controller/milestone/2)
     - [x] [wasm-shim](https://github.com/Kuadrant/wasm-shim): [v0.1.0](https://github.com/Kuadrant/wasm-shim/milestone/1)
   - [x] [limitador-operator](https://github.com/Kuadrant/limitador-operator): [v0.4.0](https://github.com/Kuadrant/limitador-operator/milestone/1)
     - [x] [limitador](https://github.com/Kuadrant/limitador): crate [v0.3.0](https://github.com/Kuadrant/limitador/milestone/1), binary [v1.0.0](https://github.com/Kuadrant/limitador/milestone/2)
   - [x] [authorino-operator](https://github.com/Kuadrant/authorino-operator): [v0.4.1](https://github.com/Kuadrant/authorino-operator/milestone/1)
     - [x] [authorino](https://github.com/Kuadrant/authorino): [v0.10.0](https://github.com/Kuadrant/authorino/milestone/1)
