### ISSUE TITLE
Defaults & Overrides

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/kuadrant-operator#431]
Extend the Kuadrant Policy APIs so we support use cases of **Defaults & Overrides (D/O)** for [Inherited Policies](https://gateway-api.sigs.k8s.io/geps/gep-713/#inherited-policy-attachment-its-all-about-the-defaults-and-overrides), including the following base use cases:
- **Defaults:** policies set at a lower level in the hierarchy supersede ones set (as "defaults") at a higher level, or "more specific beats less specific"
- **Overrides:** policies set at a higher level in the hierarchy supersede ones set at the lower levels, or "less specific beats more specific"

As well as the following derivative cases:
- **Merged defaults:** default policy rules that are merged into the more specific policies (as opposed to an atomic less specific set of rules that is activated only when another more specific one is absent)
- **Merged overrides:** override policy rules that are merged into the more specific policies (as opposed to an atomic less specific set of rules that is activated fully replacing another more specific one that is present) 
- **Constraints:** specialization of an override that rather than declaring concrete values, specify constraints for values – typically numeric values and regular patterns (e.g. limited sets) – declared at the lower levels, that is used to "clip" the requested specific values within the boundaries dictated by the constraint, in an override fashion – e.g.: min value, max value, `in` operator.
- **Deactivation:** specialization that completes a merge default use case by allowing lower level policies to disable ("deactivate") individual defaults set a higher level (as opposed to superseding those defaults with actual more specific policy rules with meaning)

Out of scope:
- **Requirements:** high level policies that declare requirements to be fulfilled by more specific (lower level) policies without specifying concrete default or override values or constraints. E.g.: "an authentication policy must be enforced, but none is provided by default."

Affected APIs:
- AuthPolicy
- RateLimitPolicy

Non-affected APIs, while these are considered Direct Policies, i.e. with no hierarchical effect:
- DNSPolicy
- TLSPolicy

### Implementation steps [wip]

- [ ] Add full overrides to the RateLimitPolicy API
- [ ] Add full overrides to the AuthPolicy API
- [ ] Change RateLimitPolicies to lists of rules (?)
- [ ] Change AuthPolicies to lists of rules (?)
- [ ] Allow multiple RateLimitPolicies to target the same object
- [ ] Allow multiple AuthPolicies to target the same object
- [ ] Merge strategy for RateLimitPolicies
- [ ] Merge strategy for AuthPolicies
- [ ] Add support for D/O conditions in the RateLimitPolicy API
- [ ] Add support for D/O conditions in the AuthPolicy API
- [ ] Add support for default deactivations in the RateLimitPolicy API
- [ ] Add support for default deactivations in the AuthPolicy API
- [ ] Tag RateLimitPolicy CRD as inherited policy attachment kind
- [ ] Tag AuthPolicy CRD as inherited policy attachment kind
- [ ] Tag DNSPolicy CRD as direct policy attachment kind
- [ ] Tag TLSPolicy CRD as direct policy attachment kind

**Comment by KevFan** [comment]
Implementation steps looks good to me to cover the RFC suggestions 👍 

I've updated the PR link for RateLimit WasmPlugin Controller as the intial PR has now been superseded by https://github.com/Kuadrant/kuadrant-operator/pull/447

**Comment by guicassolato** [comment]
About using maps vs listMapType and the effects on merging into `spec` fields, to leave no doubts, @youngnick has added an excellent example to https://github.com/kubernetes-sigs/gateway-api/pull/2813.

cc @maleck13
