### ISSUE TITLE
Gateway and policy status

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/kuadrant-operator#433]
## WHAT:

This epic is to capture this issue for all the Status pieces i.e Status for which policies are affecting the gateway and the status of the actual policies themselves

Documentation
- [ ] https://github.com/Kuadrant/kuadrant-operator/issues/432

Policy status (Showing status)

- [x] https://github.com/Kuadrant/multicluster-gateway-controller/issues/643
- [x] https://github.com/Kuadrant/multicluster-gateway-controller/issues/642

**Comment by Boomatang** [comment]
Is there any updates on this Epic?
