### ISSUE TITLE
API Observability

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/kuadrant-operator#439]
(corresponding docs epic https://github.com/Kuadrant/docs.kuadrant.io/issues/67)

Dashboards [Refined]:
- [x] https://github.com/Kuadrant/kuadrant-operator/issues/434
- [x] https://github.com/Kuadrant/kuadrant-operator/issues/435
- [x] https://github.com/Kuadrant/kuadrant-operator/issues/436
- ~https://github.com/Kuadrant/kuadrant-operator/issues/437~ (moved out of epic - see comment in issue)
- [x] #448

Alerts [Refined]: 
- [x] https://github.com/Kuadrant/kuadrant-operator/issues/440
- [x] https://github.com/Kuadrant/kuadrant-operator/issues/441

Logs & Tracing [Refined]:
- [x] https://github.com/Kuadrant/kuadrant-operator/issues/438
- [x] https://github.com/Kuadrant/kuadrant-operator/issues/442
- ~https://github.com/Kuadrant/architecture/issues/48~ (removing this from epic as it covers issues beyond the scope of this epic)

**UPDATE:** Moved remaining testing issues out of this epic
