### ISSUE TITLE
Example dashboards feedback

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/kuadrant-operator#559]
- [x] #665
- [x] #666
- [x] Change the Business User dashboard heatmap to use blue shades instead of red (avoid association with it being 'bad') https://github.com/Kuadrant/kuadrant-operator/pull/660
- [x] #667
- [x] Show duplicate Gateways, Policies and Routes in an intuitive way when more than 1 exists across clusters with the same name (e.g. assuming the same name & namespace means they are 'multi cluster'). Will need a 'cluster' label in remote write config. https://github.com/Kuadrant/kuadrant-operator/pull/664
- [x] unhealthy gateway stat panel not detecting gateway with 'accepted=false' (see 2nd screenshot) https://github.com/Kuadrant/kuadrant-operator/pull/660
- [x] Fix any m:m query errors that occur when more than 1 cluster has the same resource name & namespace (see screenshot below) https://github.com/Kuadrant/kuadrant-operator/pull/637

*m:m issue with unhealthy gateways stat panel*
![image](https://github.com/Kuadrant/kuadrant-operator/assets/878251/53e9229f-715c-4aa9-9723-38183cf2956c)

*unhealthy gateway*
<img width="898" alt="image" src="https://github.com/Kuadrant/kuadrant-operator/assets/878251/1896d44c-3765-4b27-9356-680cf47009a0">

query
```
count(gatewayapi_gateway_info unless (gatewayapi_gateway_info{exported_namespace=~"${gateway_namespace}"} * on(name, exported_namespace, instance) group_left gatewayapi_gateway_status{exported_namespace=~"${gateway_namespace}",type="Programmed"})
or ignoring(type)
gatewayapi_gateway_info unless (gatewayapi_gateway_info{exported_namespace=~"${gateway_namespace}"} * on(name, exported_namespace, instance) group_left gatewayapi_gateway_status{exported_namespace=~"${gateway_namespace}",type="Accepted"}))
```
metric
```
api_gateway_status{container="kube-state-metrics", customresource_group="gateway.networking.k8s.io", customresource_kind="Gateway", customresource_version="v1beta1", exported_namespace="ingress-gateway", instance="10.128.0.231:8081", job="kube-state-metrics-kuadrant", name="prod-web", namespace="monitoring", prometheus="openshift-user-workload-monitoring/user-workload", receive="true", replica="thanos-receive-ingestor-default-0", tenant_id="default-tenant", type="Programmed"} | 0
```

suggestion query for healthy:
```
count(
(gatewayapi_gateway_info{} * on(name, exported_namespace, instance) group_left gatewayapi_gateway_status{type="Programmed"} == 1)
and ignoring(type) 
(gatewayapi_gateway_info{} * on(name, exported_namespace, instance) group_left gatewayapi_gateway_status{type="Accepted"} == 1)
)
```
and unhealthy
```
count(
(gatewayapi_gateway_info{} * on(name, exported_namespace, instance) group_left gatewayapi_gateway_status{type="Programmed"} < 1)
or ignoring(type) 
(gatewayapi_gateway_info{} * on(name, exported_namespace, instance) group_left gatewayapi_gateway_status{type="Accepted"} < 1)
)
```
