### ISSUE TITLE
Support Installation of Kuadrant via an Operator

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-operator#75]
**Use Case**

As a cluster admin, I would like to install Kuadrant on to my OpenShift cluster so that I can provide my development teams with the tools needed to protect their services and APIs. 

**Options**

Provide an Operator available via the Operator Hub that can install the Kuadrant components onto a cluster that already has Isito installed.

Questions:
- how does gateway API get installed on the cluster (cluster admin could probably do this but it needs to be a clear pre-req) another option might be to have it installed by the operator installing Istio.

**Demo**

- Show a cluster with Isito pre installed
- Show installing the kuadrant operator via OLM
- Show Kuadrant is configured on the cluster (Authorino is registered as an AuthProvider)
- Show the kuadrant CRDS as available

**Done**

- [x] Kuadrant Operator that can install the kuadrant components (Limitador, Kuadrant Controller, Authorino)
- [x] Kuadrant/kuadrant-controller#150
- [x] Kuadrant/kuadrant-controller#148
- [x] Kuadrant/kuadrant-controller#149
- [x] Kuadrant/kuadrant-operator#76
- [x] Kuadrant/kuadrant-controller#157
- [x] [ Kuadrant Operator is available via Operator Hub](https://github.com/Kuadrant/kuadrant-operator/issues/19)
