### ISSUE TITLE
CEL

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/kuadrant-operator#800]
- [x] #801
  - Data retrieval
  - Predicates
  - String interpolation
- [x] [Impl CEL in Authorino](https://github.com/Kuadrant/authorino/issues/475)
- [x] [Auth in Wasm](https://github.com/Kuadrant/wasm-shim/issues/58)
- [x] [Support CEL in top level conditions (predicates) in Wasm](https://github.com/Kuadrant/wasm-shim/pull/113)
- [x] #978
  - [x] [RateLimitPolicy](https://github.com/Kuadrant/kuadrant-operator/issues/951)
  - [x] [AuthPolicy](https://github.com/Kuadrant/kuadrant-operator/pull/971)
- [x] #979
- [x] #980

**Comment by alexsnaps** [comment]
Relates to #758

**Comment by Boomatang** [comment]
The last unchecked task, RateLimitPolicy links to a closed task. Does this mean everything has being done? and that we can close this issue?
