### ISSUE TITLE
Documentation for first Kuadrant milestone

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-operator#92]
Captures the tasks around documentation we need for the first milestone release

- [ ] [Installation guide using the operator](https://github.com/Kuadrant/kuadrant-operator/issues/76)
- [ ] [Installation guide for Kubernetes  using the operator](https://github.com/Kuadrant/kuadrant-operator/issues/76)
- [ ] Kuadrant/kuadrant-operator#93
- [ ] Kuadrant/kuadrant-operator#94
- [ ] General troubleshooting / Known issues and FAQ
- [ ] Developer Guide for contributing
